---
collections:
  - name: ansible.posix
    version: 1.6.1
  - name: community.docker
    version: 4.0.0
  - name: community.general
    version: 9.5.0
  - name: ericsysmin.docker
    version: 1.0.0
  - name: grafana.grafana
    version: 5.5.1
  - name: prometheus.prometheus
    version: 0.19.0

roles:
  - name: geerlingguy.firewall
    src: https://github.com/geerlingguy/ansible-role-firewall.git
    version: master
  - name: oefenweb.fail2ban
    src: https://github.com/Oefenweb/ansible-fail2ban.git
    version: master
