---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 9.1.0
  - name: containers.podman
    version: 1.15.4
  - name: grafana.grafana
    version: 5.2.0
roles:
  - name: geerlingguy.firewall
    src: https://github.com/geerlingguy/ansible-role-firewall.git
    version: master
  - name: oefenweb.fail2ban
    src: https://github.com/Oefenweb/ansible-fail2ban.git
    version: master
