---
collections:
  # keep-sorted start
  - name: ansible.posix
    version: 2.0.0
  - name: community.docker
    version: 4.0.1
  - name: community.general
    version: 10.0.1
  - name: ericsysmin.docker
    version: 1.0.0
  - name: grafana.grafana
    version: 5.6.0
  - name: prometheus.prometheus
    version: 0.23.0
  # keep-sorted end

roles:
  - name: geerlingguy.firewall
    src: https://github.com/geerlingguy/ansible-role-firewall.git
    version: master
