---
collections:
  # keep-sorted start
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 5.0.4
  - name: community.general
    version: 12.2.0
  - name: grafana.grafana
    version: 6.0.6
  - name: prometheus.prometheus
    version: 0.27.5
  # keep-sorted end

roles:
  - name: geerlingguy.firewall
    version: 2.7.0
